### DISCUSSION TITLE
What should be notified in feishu?

### DISCUSSION THREAD

**Discussion by Samuka007** [faas-rs/faasd-in-rust#33] [General]
@oeasy1412 @Vitus213 @dolzhuying @sparkzky @kaleidoscope416 
What event do you guys think should be added to feishu notification?
In https://github.com/marketplace/actions/github-events-to-feishu-bot-action,
we have these events:
```yaml
name: feishu bot

on:
  branch_protection_rule:
    types: [created, deleted]
  check_run:
    types: [rerequested, completed]
  check_suite:
    types: [completed]
  create:
  delete:
  deployment_status:
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created, deleted]
  fork:
  gollum:
  issues:
    types: [opened, edited, milestoned, pinned, reopened]
  issue_comment:
    types: [created, deleted]
  label:
    types: [created, deleted]
  merge_group:
    types: [checks_requested]
  milestone:
    types: [opened, deleted]
  page_build:
  project:
    types: [created, deleted, reopened]
  project_card:
    types: [created, deleted]
  project_column:
    types: [created, deleted]
  public:
  pull_request:
    branches: ['main']
    types: [opened, reopened]
  pull_request_review:
    types: [edited, dismissed, submitted]
  pull_request_review_comment:
    types: [created, edited, deleted]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: ['main']
  registry_package:
    types: [published]
  release:
    types: [published]
  status:
  watch:
    types: [started]
  schedule:
    - cron: '30 2 * * *'

jobs:
  send-event:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: junka/feishu-bot-webhook-action@main
        with:
          webhook: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          signkey: ${{ secrets.FEISHU_BOT_SIGNKEY }}
```

**Comment by Vitus213** [comment]
issue,pr,push

**Comment by Samuka007** [comment]
https://github.com/faas-rs/faasd-in-rust/tree/feat-feishu_notify
在这个分支上继续工作吧

另外，我其实是想同步两边的信息，类似
```yaml
on:
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  deployment_status:
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created]
  issues:
    types: [opened, edited, milestoned, pinned, reopened]
  issue_comment:
    types: [created]
  milestone:
    types: [opened, deleted]
  project_card:
    types: [created]
  pull_request:
    branches: ['main']
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: ['main']
```
